### ISSUE TITLE
Out of Stock filter not working

### ISSUE THREAD

**Issue by alvaialex** [tzyganu/stock-filter#2] opened 2015-02-23 10:35 UTC
I have installed this module. Its working Fine. Out of Stock is not working that url is coming empty. But in stock is working fine.
Please help me.

Thanks !
Alex

**Comment by tzyganu** [comment] 2015-02-23 10:42
@alvaialex First make sure that the "Show out of stock products" flag is set to yes in System->Configuration->Inventory->Stock Options.  
then make sure your indexes are up to date.

**Comment by ghost** [comment] 2015-05-23 12:43
Hello tzyganu 
i install and select Show out of stock products .but dont show in my frontend
regards

**Comment by alvaialex** [comment] 2015-05-28 03:53
Hi Tzyganu,

Thanks for your response. In my product listing page all products are listing. instock product as well as out of stock products, but out of stock filter not working.

Thanks  
Alex

**Comment by tzyganu** [comment] 2015-05-28 06:53
@alvaialex What Magento version are you using? Are the indexes up to date?

**Comment by alvaialex** [comment] 2015-05-28 07:42
Hi Tzyganu,

Magento Community edition 1.9.0.1 

Yes, indexing up to date. clear catch also.

Thanks 
Alexander

**Comment by tzyganu** [comment] 2015-05-28 08:26
The filter is not working or the filter option is not appearing? I cannot reproduce the issue. It works fine on my install. Do you have any other extensions related to layered navigation?

**Comment by alvaialex** [comment] 2015-05-28 08:35
Filter is not appearing. Also i have installed amasty layered navigation pro extension.

**Comment by tzyganu** [comment] 2015-05-28 08:38
There is a chance that the amasty extension is not compatible with my extension (or the other way around). Try disabling that extension and see if it works. Also make sure that the stock filter extension is enabled from system->configuration.

**Comment by alvaialex** [comment] 2015-05-28 08:40
When i am install magento fresh pack its working fine. 
Is there any chance to combine both extension :)

**Comment by tzyganu** [comment] 2015-05-28 08:51
Sorry, but I don't have access to the amasty extension and making them compatible is not in the scope of this extension.  
I guess you cannot use both. 
I will close this issue since is not related to the extension itself.

**Closed as completed by tzyganu** 2015-05-28 08:51 UTC

**Comment by alvaialex** [comment] 2015-05-28 08:53
Hi tzyganu, 

Thank you very much. Thanks for your time.
I will try to do that.
